### ISSUE TITLE
Technical Issue #1: Some images "width" set as percentage -- resulting in variable appearance

### ISSUE THREAD

**Issue by jdoggett1** [ronaldliujr/My-Personal-Project#1]
https://github.com/ronaldliujr/My-Personal-Project/blob/64b7532097db3a4f5d3e7baa5ec5e6f25d573586/styles/history.css#L11

The width of your images seems to be set as a percentage in your CSS sheet. This results in the image being stretched to an undesirable appearance (please see screenshots attached).

I would suggest changing the width to a "px" value, for example. Experimenting with "min-width" and "max-width" may help you achieve your desired outcome.

<img width="2548" alt="Screen Shot 2022-11-08 at 4 14 41 PM" src="https://user-images.githubusercontent.com/112436121/200677299-cc9bfbb1-02ce-4e9b-80e8-3bad53d176a6.png">
<img width="589" alt="Screen Shot 2022-11-08 at 4 14 50 PM" src="https://user-images.githubusercontent.com/112436121/200677301-c9838c4f-4c15-4c36-bf8e-903846c8e1e3.png">

**Comment by ronaldliujr** [comment]
Ahh, I see. I forgot to consider what my website would look like from other devices, as I was always editing on my Babson laptop. I look into the suggestions you made for this and see if that fixes the issue. Thanks for bringing it up!
