### ISSUE TITLE
Content Issue #2: Videos on "Highlights" page not centered

### ISSUE THREAD

**Issue by jdoggett1** [ronaldliujr/My-Personal-Project#2]
https://github.com/ronaldliujr/My-Personal-Project/blob/64b7532097db3a4f5d3e7baa5ec5e6f25d573586/styles/highlights.css#L1

This is only a minor suggestion. The contents of the other pages on your site are nicely centered. To keep consistent with this, I would suggest centering the content in your CSS sheet. Using `display: flex;` may be helpful.

**Comment by ronaldliujr** [comment]
I originally had everything on that page centered, but did not really like the look of the captions and videos being centered. I might look to play with this a bit to keep more consistency with my entire website.
