### ISSUE TITLE
Technical Issue #2: Clicking FCB crest results in no action

### ISSUE THREAD

**Issue by jdoggett1** [ronaldliujr/My-Personal-Project#4]
https://github.com/ronaldliujr/My-Personal-Project/blob/64b7532097db3a4f5d3e7baa5ec5e6f25d573586/highlights.html#L31

I just noticed when clicking the FC Barcelona crest (on the highlights page, for example) nothing happens. I'm not sure if you intend for this to act as a home button, but would suggest adding a link to homepage (index).

**Comment by ronaldliujr** [comment]
I did intend for the crest to act as a second home button, but I realize now that I forgot to actually link it back to my index.html page. Thanks for bringing that to my attention!
